"""Layer model: per-layer operation type and laser parameters.

The UI keeps an ordered list of layers; every imported object carries a
`layer_id`. The planner groups paths by layer and respects layer order.
Disabled and frame-only layers are visible but never emit. Raster layers
emit hatch lines generated by `mopa_luiz.raster` from their closed input
shapes.
"""

from __future__ import annotations

import math
from dataclasses import asdict, dataclass, field
from typing import Iterable

from .cli import MarkConfig
from .safety import validate_layer_settings


VECTOR_ENGRAVE = "vector_engrave"
VECTOR_CUT = "vector_cut"
RASTER_ENGRAVE = "raster_engrave"
FRAME_ONLY = "frame_only"
DISABLED = "disabled"
OPERATIONS = (VECTOR_ENGRAVE, VECTOR_CUT, RASTER_ENGRAVE, FRAME_ONLY, DISABLED)


@dataclass
class LayerSpec:
    layer_id: str
    name: str
    operation: str
    power_percent: float
    frequency_khz: float
    pulse_width_ns: float
    speed_mm_s: float
    passes: int = 1
    visible: bool = True
    output: bool = True
    color: str = "#26d0a8"
    air_assist: bool = False
    raster_pitch_mm: float = 0.1
    raster_angle_deg: float = 0.0
    raster_angle_step_deg: float = 90.0

    def emits_when_marking(self) -> bool:
        if not self.output:
            return False
        if self.operation in {DISABLED, FRAME_ONLY}:
            return False
        return True

    def to_dict(self) -> dict[str, object]:
        return asdict(self)


def default_layers() -> list[LayerSpec]:
    return [
        LayerSpec(
            layer_id="vector-engrave",
            name="Vector Engrave",
            operation=VECTOR_ENGRAVE,
            power_percent=100.0,
            frequency_khz=30.0,
            pulse_width_ns=200.0,
            speed_mm_s=1000.0,
            color="#26d0a8",
        ),
        LayerSpec(
            layer_id="vector-cut",
            name="Vector Cut / Deep Mark",
            operation=VECTOR_CUT,
            power_percent=100.0,
            frequency_khz=30.0,
            pulse_width_ns=200.0,
            speed_mm_s=300.0,
            color="#e2b84b",
        ),
        LayerSpec(
            layer_id="raster",
            name="Raster",
            operation=RASTER_ENGRAVE,
            power_percent=100.0,
            frequency_khz=30.0,
            pulse_width_ns=200.0,
            speed_mm_s=1000.0,
            output=True,
            color="#7aa2ff",
            raster_pitch_mm=0.1,
            raster_angle_deg=0.0,
            raster_angle_step_deg=90.0,
        ),
        LayerSpec(
            layer_id="frame-only",
            name="Frame Only",
            operation=FRAME_ONLY,
            power_percent=0.0,
            frequency_khz=30.0,
            pulse_width_ns=200.0,
            speed_mm_s=1000.0,
            color="#93a09c",
        ),
    ]


def layer_from_dict(payload: dict) -> LayerSpec:
    operation = str(payload.get("operation", VECTOR_ENGRAVE))
    if operation not in OPERATIONS:
        raise ValueError(f"unknown layer operation: {operation}")
    return LayerSpec(
        layer_id=str(payload.get("layer_id") or payload.get("id") or "layer"),
        name=str(payload.get("name", "Layer")),
        operation=operation,
        power_percent=float(payload.get("power_percent", 1.0)),
        frequency_khz=float(payload.get("frequency_khz", 30.0)),
        pulse_width_ns=float(payload.get("pulse_width_ns", 200.0)),
        speed_mm_s=float(payload.get("speed_mm_s", 1000.0)),
        passes=int(payload.get("passes", 1)),
        visible=bool(payload.get("visible", True)),
        output=bool(payload.get("output", True)),
        color=str(payload.get("color", "#26d0a8")),
        air_assist=bool(payload.get("air_assist", False)),
        raster_pitch_mm=float(payload.get("raster_pitch_mm", 0.1)),
        raster_angle_deg=float(payload.get("raster_angle_deg", 0.0)),
        raster_angle_step_deg=float(payload.get("raster_angle_step_deg", 90.0)),
    )


def validate_layers(
    layers: Iterable[LayerSpec],
    cfg: MarkConfig | None,
) -> dict[str, list[str]]:
    """Per-layer validation. Returns layer_id -> list of errors."""
    errors: dict[str, list[str]] = {}
    for layer in layers:
        layer_errors = validate_layer_settings(
            operation=layer.operation,
            power_percent=layer.power_percent,
            frequency_khz=layer.frequency_khz,
            pulse_width_ns=layer.pulse_width_ns,
            speed_mm_s=layer.speed_mm_s,
            cfg=cfg,
        )
        if layer.operation == RASTER_ENGRAVE and layer.output:
            if layer.raster_pitch_mm <= 0:
                layer_errors.append("raster pitch must be > 0 mm")
            if not math.isfinite(layer.raster_angle_deg):
                layer_errors.append("raster angle must be a finite number")
            if not math.isfinite(layer.raster_angle_step_deg):
                layer_errors.append("raster angle step must be a finite number")
        if layer_errors:
            errors[layer.layer_id] = layer_errors
    return errors


@dataclass
class LayerJob:
    layer: LayerSpec
    polylines: list[list[tuple[float, float]]]


def group_by_layer(
    objects: list[dict],
    layers: list[LayerSpec],
) -> list[LayerJob]:
    """Group transformed object polylines by layer in the layers' declared order.

    `objects` is a list of dicts with at least `layer_id` and `polylines`
    (already transformed into mm world coordinates by the caller).
    Objects whose `layer_id` does not match any layer are dropped silently.
    """
    by_id = {layer.layer_id: layer for layer in layers}
    buckets: dict[str, list[list[tuple[float, float]]]] = {layer.layer_id: [] for layer in layers}
    for obj in objects:
        layer_id = str(obj.get("layer_id") or "")
        if layer_id not in by_id:
            continue
        polylines = obj.get("polylines") or []
        for poly in polylines:
            cleaned = [(float(x), float(y)) for x, y in poly if len(poly) >= 2]
            if len(cleaned) >= 2:
                buckets[layer_id].append(cleaned)
    return [LayerJob(layer=by_id[lid], polylines=buckets[lid]) for lid in by_id]


def emitting_jobs(jobs: list[LayerJob]) -> list[LayerJob]:
    return [job for job in jobs if job.layer.emits_when_marking() and job.polylines]


def framing_jobs(jobs: list[LayerJob]) -> list[LayerJob]:
    """Layers that should be included when red-light framing the workspace."""
    keep = []
    for job in jobs:
        layer = job.layer
        if not layer.visible:
            continue
        if layer.operation == DISABLED:
            continue
        if not job.polylines:
            continue
        keep.append(job)
    return keep
